 
cc_binary(
    name="HelloMediapipe",
    srcs=["main.cpp"],
    deps = [
        "@mediapipe_repository//mediapipe/calculators/core:pass_through_calculator",
        "@mediapipe_repository//mediapipe/framework/port:logging",
        "@mediapipe_repository//mediapipe/framework/port:parse_text_proto",
        "@mediapipe_repository//mediapipe/framework/port:status",
    ],
)
