cc_binary(
    name = "HelloMediapipe",
    srcs = ["main.cpp"],
    deps = [
        "//Calculators:http_test_calculator",
        "@mediapipe_repository//mediapipe/framework/port:logging",
        "@mediapipe_repository//mediapipe/framework/port:parse_text_proto",
        "@mediapipe_repository//mediapipe/framework/port:status",
    ],
)
